### ISSUE TITLE
Unable to install on Node V 0.10.29 - probable user error

### ISSUE THREAD

**Issue by boobboo** [slackhq/node-slack-client#100]
Hi, 

I am trying to run a Slackbot server on my Raspberry Pi2, below is an error I am getting when installing using NPM.

Is there a dependency upon the node version which I cannot see? I have installed all the optional dependencies, although Coffee-Script and WS are at a higher level than required.

Thanks

Chris

pi@raspberrypi3:~ $ sudo npm install slack-client
npm WARN package.json log@1.4.0 No repository field.

> utf-8-validate@1.2.1 install /home/pi/node_modules/slack-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/slack-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
validation.target.mk:84: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/home/pi/node_modules/slack-client/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/node_modules/slack-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

> bufferutil@1.2.1 install /home/pi/node_modules/slack-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/slack-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
bufferutil.target.mk:84: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/home/pi/node_modules/slack-client/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/node_modules/slack-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.2.1
slack-client@1.5.1 node_modules/slack-client
├── coffee-script@1.9.3
└── ws@0.8.1 (options@0.0.6, ultron@1.0.2)

pi@raspberrypi3:~ $ sudo npm install coffee-script
npm WARN package.json log@1.4.0 No repository field.
coffee-script@1.10.0 node_modules/coffee-script

pi@raspberrypi3:~ $ sudo npm install ws
npm WARN package.json log@1.4.0 No repository field.
ws@1.0.1 node_modules/ws
├── options@0.0.6
└── ultron@1.0.2

**Comment by l12s** [comment]
There's a thread here that may solve your issues: https://github.com/nodejs/nan/issues/414

**Comment by l12s** [comment]
Closing for now - let me know if that link didn't help or if we can give you any more insight into how to install.
