### ISSUE TITLE
Add ability to update messages

### ISSUE THREAD

**Issue by fabianthoma** [slackhq/node-slack-client#11]
To be able to add update functionallity to messages there needs to be a capability put into place in this library. Please see slackhq/hubot-slack#91 for the requirements in hubot.
I'd be happy to implement this capability, however I don't understand in which ways the message can be updated. I've found this method, but it uses the HTTP API: https://api.slack.com/methods/chat.update Is there also a way to do this via the realtime API?

**Comment by paulhammond** [comment]
There isn't a way to update a message using the real time API, but the API token used by node-slack-client can also make calls to the web API, including the chat.update method. Take a look at the places in the code where `@_client._apiCall` appears for some examples!

**Comment by paulhammond** [comment]
I just realized you already implemented this in #14. Thanks!
