### ISSUE TITLE
2.0.0: npm install not working

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#113]
Hey guys, 
I'm trying to install the 2.0.0-beta1 version via npm install and it is generating a version not found error.

Wasn't suppose to be a release called 2.0.0-beta1?

**Comment by vanm** [comment]
Check out
https://github.com/peernohell/node-slack-client/commit/9ba870044c6083800f6129c4bd064b1ab99583c3

**Comment by l12s** [comment]
Sorry, my bad.

Once we get the release done I'm going to script up the release process so that I stop missing things like this.
