### ISSUE TITLE
how to pass arguments to webclient?

### ISSUE THREAD

**Issue by remipou** [slackhq/node-slack-client#114]
trying `web.reactions.add({'name':'thumbsup', 'channel':channel, 'timestamp':ts, 'pretty':'1'}, function(err, data){});` but nothing happens...
(2.0.0beta)

**Comment by ekmartin** [comment]
Think it would be `web.reactions.add('thumbsup', { channel: channel, timestamp: ts }, function(err, data) {});`. See https://github.com/slackhq/node-slack-client/blob/2.0.0-beta/lib%2Fclients%2Fweb%2Ffacets%2Freactions.js#L20-L39 for more information.

**Comment by remipou** [comment]
thank you!
