### ISSUE TITLE
2.0.0 how to instantiate DataSource or LegacyRTMClient

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#119]
Hi, guys. I created a branch to test the new version of the client and I am running into some doubts:

1 - I want to instantiate a SlackDataStore to access all the information from the version 1 (team, users, dm, etc), but SlackDataStore is not being exported in the module and haven't seen a full example on how to user it (it would be really cool if the examples directory had one).

2 - I also found in the code the LegacyRTMClient (which already takes care of the MemoryDataStore), but also this class (as far as I understood) is not being exported in slack-client/index.js

**Comment by acemtp** [comment]
i sent a PR about this https://github.com/slackhq/node-slack-client/pull/118

**Comment by acemtp** [comment]
The PR was applied so it's fixed

**Comment by brunosiqueira** [comment]
@l12s : should there be a new beta package version? Eg: @2.0.0-beta.4

**Comment by l12s** [comment]
Yep, my bad - just released one.
