### ISSUE TITLE
2.0.0 getDMByName don't exist anymore

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#126]
Hey, guys

Testing the beta version, I realized the the client does not have the method getDMByName(). I also checked that the dataStore can provide the already loaded DMs by ID.

The thing is, I don't have the DM id, only the user's slack_id. Of course I can get the hash and iterate looking for the user's name, but would be interesting if this was encapsulated in the client.

But the most important thing is: with my experience in the last slack client version, when the DM do not exist yet, when we call it for the first time, it is created at slack and updated in the client (right?). This way now it seems like once loaded it is static and do not  update itself.

Can you advise on this?

**Comment by l12s** [comment]
Looking at the old implementation now

**Comment by l12s** [comment]
Ok, so the old function did this:

```
  getDMByName: (name) ->
    for k of @dms
      if @dms[k].name == name
        return @dms[k]
```

So, as far as I can tell, this function didn't create a new DM when you call it. Can you explain a bit more by what you mean by it creating and updating in the client?

**Comment by l12s** [comment]
The commit above adds getDMByName back in. I'm not certain what you're asking on the other part though, so will wait to hear back before I close this issue.

**Comment by brunosiqueira** [comment]
@l12s I guess you are right. This is what the method di. Thanks for recreating it
