### ISSUE TITLE
2.0.0 dm.send(message) - it changed

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#132]
I want to sent a direct message to a user form my bot. I used to do "dm.send(message)", but the structure changed.

I'm reading the new code and I see that there's a postMessage() method in ChatFacet, but I am not really sure on how to use or to call it from the client api. The example does not have this part.

Could you guys give a quick help with that?

**Comment by l12s** [comment]
Yeah, the new model objects are designed to avoid being tightly couple with the client, so they don't have things like `send` attached to them.

You have a couple options for this. The closest analogy to what the old client did would be to use the `sendMessage` function I just added to the RTM Client with this commit: https://github.com/slackhq/node-slack-client/commit/1231d83242cd1d762c19822820b7c059c622686a

I'll push a new beta shortly, that'll wrap that + a few other changes for you to use.

**Comment by l12s** [comment]
Ok, you can now `npm install slack-client@2.0.0-beta.8` and use the `sendMessage` function on the rtm client.

Just make sure that the client has connected fully before you try - you can listen for it to emit the `RTM_CONNECTION_OPENED` event to be sure.
