### ISSUE TITLE
2.0.0 close callback not being called

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#134]
One test I ran occasionally with the old client was to disable the wifi in my computer and turn it on again later to test how the application reconnects.

I am running this test with the new client and I noticed the 'close' callback is not being called, even though I implemented it in my application.

        this.slack.on("close", (code, reason) => {
          console.log('connection closed' + code + ' - ' + reason)
          this.slack.reconnect()
        })

The callback now passes a code and a reason and I wanted to use this information to check if the app has been removed from slack or if it is juts a connection problem.

**Comment by l12s** [comment]
Ok, will take a look at what's happening.

**Comment by l12s** [comment]
Ok, I took a quick look at this.

So, two things:
- the `close` event is now more specific and is `ws_close` or `require('slack-client').EVENTS.CLIENT.RTM.WS_CLOSE`
- the callback you have to deal with the disconnection _should_ be invoked much much less frequently as the reconnect behavior within the app has been made a lot more robust

I need to do a few things in response I think:
- make the events namespaces a bit less verbose
- document the RTM client event lifecycle
- add an event for "we retried a whole bunch and things are still broken", so your call what you want to do
- add some logging to cover events in the RTM client

That's a moderately involved change, so I'll try and take a look this evening

**Comment by l12s** [comment]
https://github.com/slackhq/node-slack-client/commit/ef00728d948aeff940c821c38632cab39c2a249b addresses this.

You'll need to listen to the `DISCONNECT` event to get the behavior you used to have.

**Comment by brunosiqueira** [comment]
Hey, @I12s. Thank you for the feedback. I tested the disconnect callback and it is being called correctly when the app is removed from slack.
But I am receiving the following parameter: "unrecoverable failure connecting to the RTM API: account_inactive".

It would be interesting to have a parameter as the text reason and another with the error code from slack. Like the WS_ERROR event that has the error param with just the code (eg: error = 'account_inactive')

**Comment by l12s** [comment]
Yep, that makes a lot of sense.

https://github.com/slackhq/node-slack-client/commit/24e5c96033632ac148f30364c03f89f66f69a46d adds this. I have some other PRs and issues to check out, so if there are some other small changes I'll batch them up and push out `2.0.2`
