### ISSUE TITLE
2.0.0 users.list not working

### ISSUE THREAD

**Issue by wrongtarget** [slackhq/node-slack-client#136]
Calling `users.list` results in — nada. No response or error is printed to the console and I don't seem to have any problems with other methods using the client. 
For example, here:

```
web.team.info(function teamInfoCb(err, channels) {
    if (err) return console.log('Error:', err);
    console.log('Team Info:', channels);
});

web.users.list(function userListCb(err, response) {
    if (err) return console.log('Error:', err);
    console.log('List', response);
})
```
...the team info is printed but not the users.list info.

**Comment by wrongtarget** [comment]
My bad. I was not passing an opts parameter (empty in this case):

```
web.users.list({}, function userListCb(err, response) {
    if (err) return console.log('Error:', err);
    console.log('List', response);
})
```

**Comment by l12s** [comment]
I believe that call actually has a signature like:

```js
/**
 * Lists all users in a Slack team.
 * @see {@link https://api.slack.com/methods/users.list|users.list}
 *
 * @param {?} optPresence Whether to include presence data in the output
 * @param {function} optCb Optional callback, if not using promises.
 */
UsersFacet.prototype.list = function list(optPresence, optCb) {
```

... so would take a boolean rather than an opts object there.

**Comment by l12s** [comment]
Given that the first arg is an opt, it should check the # of args passed, so I'm going to reopen this and add some logic to do that.

**Comment by l12s** [comment]
https://github.com/slackhq/node-slack-client/commit/2a13901b5e7d94bc154d05d89efd5a4d8cbe0d6f fixes this properly
