### ISSUE TITLE
Support promises as well as callbacks

### ISSUE THREAD

**Issue by l12s** [slackhq/node-slack-client#139]

**Comment by pcothenet** [comment]
The inline jsdoc code says: 
```
 * @param {function} optCb Optional callback, if not using promises.
```

but I  get `Uncaught TypeError: Cannot read property 'then' of undefined`. 

Should I assume this is not actually implemented?

**Comment by l12s** [comment]
Correct. It was in an earlier version of the 2.0.0 rewrite but I removed it to focus down on what the change would do. Apparently I forgot to clean up some JSDoc though.

I'll be adding promise support back in for 2.1.0 though.

**Comment by l12s** [comment]
Ok, so https://github.com/slackhq/node-slack-client/tree/add_promises adds in promise support for web API calls.

Question for you - would you want to see results where the Slack API response looks like:

```
{ok: false, error: "blah"}
```

... go to the promise error handler or the then handler?

My inclination is to have those cases go to the then and have users have an if statement to pick the issue up.

**Comment by Everesty** [comment]
I think it would make more sense to recognise it and give it  to the promise error handler, then do the same for regular callbacks.

After all, giving it to the then handler just forces users to clog up code with an extra if statement to recognise an error, which really shouldn't happen.

Added on to that, getting an `ok: false` is technically still an error, as it stops you from getting any of the data you request for, so it should be treated as one, regardless of promise or callback.

**Comment by paulcbetts** [comment]
For sure the error handler, we should turn all `ok: false`s into a `SlackApiError` that has the error text as the message

**Comment by l12s** [comment]
@paulcbetts / @Everesty - agreed, that seems reasonable. I've updated the PR to reflect that.

I need to update the RTM client so that it won't break if you create one with usePromises true, or default it to false, but this should be ready for use this weekend.

**Comment by peernohell** [comment]
I'm not fan of adding a boolean to enable/disable promise. Libs I see offering the 2 options detect if the last arguments (the callback) is defined and if it is not the case it return a promise.
You can also always use a promise and if a callback is given make a 
```
promise.then(function (result) {
  optCb(null, result)
}, function (error) {
  optCb(error);
});

return promise;
```

**Comment by l12s** [comment]
Yep, that sounds totally reasonable. I already have a check for if a callback was passed in, so I can just put the logic for creating promises there.

**Comment by l12s** [comment]
This is now fixed. I'll close this once I release the 2.1.0 version
