### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sa-mao** [slackhq/node-slack-client#144]
Guys is there any documentation for this client. I started using it on a small project I have a while ago but it seems like lot of things changed. it would be nice if there some docs somewhere. Thanks in advance :)

**Comment by l12s** [comment]
I'd suggest you check out:
- https://github.com/slackhq/node-slack-client/blob/master/CHANGELOG.md
- https://github.com/slackhq/node-slack-client/blob/master/README.md
- https://github.com/slackhq/node-slack-client/tree/master/examples

If there are specific questions that you don't see answered in there that you'd like more detail on, please create another issue requesting docs for that area and I can write something up and add it to the README / examples directory.

**Comment by sa-mao** [comment]
thanks for your reply :) but it could be nice to have some reference for the API generally speaking.

**Comment by l12s** [comment]
For the general API, there's https://api.slack.com/methods

The individual methods in the web client facets also have JSDoc annotations that provide a similar level of detail. If you wanted, you could run a JSDoc generator over those? At some point we'll get to doing that on our side and have a github pages or similar location for it.

**Comment by l12s** [comment]
Closing this for now, let me know if there are specific documentation areas that you'd like to see addressed and I can see what I can do.
