### ISSUE TITLE
jsdocs for logger not quite correct

### ISSUE THREAD

**Issue by pekim** [slackhq/node-slack-client#146]
https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js#L44
```javascript
/**
 ...
 * @param {Function} opts.logger Function to use for log calls, takes (logLevel, logString)
```

This isn't quite right. The logger is expected to be an object, with a number of functions. There are some calls to the logger that call a `log(logLevel, logString)` function on the logger object. There are also some that call an info/error/verbose/... function on the logger.  For example, https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js#L229
```javascript
      this.logger.info('unable to RTM start, attempting reconnect: ' + err || data.error);
```

This isn't a big deal, and once I realised it I changed my logger to accommodate it.

Perhaps the jsdoc comment could be changed to reflect that a winston style logger is expected? Or maybe all of the log calls changed to match the docs?

**Comment by l12s** [comment]
This is actually my bad. it should have been a function, but I forgot that and did a tidy-up commit at one point that switched off using the raw function like `logger(level, item)` to use `logger.verbose(item)` instead.

I'll try and look at swapping that back so the JSDoc is correct tomorrow.

**Comment by pekim** [comment]
Thank you.
