### ISSUE TITLE
process.env.SLACK_API_TOKEN ??!

### ISSUE THREAD

**Issue by benzmuircroft** [slackhq/node-slack-client#147]
I would like to connect with a token as an object instead please. I don't like or understand why I must use some weird node thing when I could just write the token, client id, secret into my server side js file.

please just tell me how to connect to you in a normal way. I just wan't to code to get my job done - not learn obscure low level node stuff

thanks

**Comment by benzmuircroft** [comment]
or a string

anything normal? like most if not all other apis...

**Comment by l12s** [comment]
It's the way you access environment variables in node. You can also pass in a string in it's place.

`var token = process.env.SLACK_API_TOKEN || '';` is equivalent to `var token = '...';;`

**Comment by Everesty** [comment]
I don't think you understand what [`process.env`](https://nodejs.org/api/process.html#process_process_env) is. Basically, it allows access to the shell environment variables.

In the example, they use it to indicate that a string should be given, but that string can be many different things (and should be private), so they put that there instead. The example works if you set that environment varible.

In any case, the token is a string.

**Comment by benzmuircroft** [comment]
look at this http://stackoverflow.com/questions/35687284/hard-code-slack-api-token-into-javascript-code/35687332#35687332 I have already tried to put my token as a string

**Comment by l12s** [comment]
Yep, also what @Everesty highlights is also important. It's generally good practice to make sure your tokens / secrets etc are referenced in a way that means you won't accidentally check them in or otherwise expose them publicly.

In the examples, I did this by referencing an environment variable, but you could also try using a library like https://github.com/lorenwest/node-config

**Comment by benzmuircroft** [comment]
my code is private server side code. i wont accidentally expose them publicly lol

**Comment by l12s** [comment]
I assume that you're writing a bot, so I'd suggest checking out:
* https://api.slack.com/bot-users (especially the "Setting up your bot user" section)
* https://api.slack.com/tokens

**Comment by benzmuircroft** [comment]
no im writing an app

**Comment by benzmuircroft** [comment]
connecting to you with the apps token as a string fails with `[Error: invalid_array_arg]`

**Comment by l12s** [comment]
Ok, well I'd start at the "Writing an App" page on the API site: https://api.slack.com/slack-apps

That has documentation and info on what's involved.

**Comment by l12s** [comment]
Can you give me a bit more context on what you're passing in as an app token and where you got that token from?

**Comment by benzmuircroft** [comment]
I'm using your code on the README.md I have registered my app already, read all of that about the apps...

I got my token here https://api.slack.com/docs/oauth-test-tokens

**Comment by benzmuircroft** [comment]
var RtmClient = require('slack-client').RtmClient;
    var token = 'xoxp-xxxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxx';
    var rtm = new RtmClient(token, {logLevel: 'debug'});
    rtm.start();

gives me `[Error: invalid_array_arg]`

**Comment by l12s** [comment]
Which version of `slack-client` are you running?

**Comment by benzmuircroft** [comment]
"version": "2.0.2" installed today

**Comment by l12s** [comment]
Ok, so the below code snippet works for me:

```
var RtmClient = require('slack-client').RtmClient;

var token = 'xoxp-12611402179-12617794258-14984632099-ccb7dd07db';
var rtm = new RtmClient(token, {logLevel: 'debug'});
rtm.start();
```

(for reference, that token has been revoked, so won't work for you)

**Comment by benzmuircroft** [comment]
that's the same code mate!

**Comment by l12s** [comment]
Could you send me the full stacktrace that you're getting? What I'm suggesting is that the error is probably somewhere else given that my sample code is working there.

**Comment by benzmuircroft** [comment]
don't know how with that code it's weird all your code is very weird! LOL

**Comment by benzmuircroft** [comment]
console.trace(what goes here) ?

**Comment by l12s** [comment]
When you see the `[Error: invalid_array_arg] undefined` error, is there any other context around it? Any other lines printed out etc?

Could you also try accessing this URL https://slack.com/api/rtm.start?token=xoxp-xxx&pretty=1 (replacing xoxp-xxx with your token) and let me know what happens?

**Comment by benzmuircroft** [comment]
yeah just this `[Error: invalid_array_arg] undefined`

**Comment by benzmuircroft** [comment]
not very informative... what if i could throw an error somehow?? maybe we would get more info (not sure)

**Comment by benzmuircroft** [comment]
or could i create a token with oauth?

**Comment by l12s** [comment]
Is the token you're using not an oauth tester token - you can create them via https://api.slack.com/docs/oauth-test-tokens

**Comment by benzmuircroft** [comment]
it is, as, I gave you the link to the test token page earlier where slack generated it for me

**Comment by l12s** [comment]
Ok, do you mind sending me the token you're using via email to leah@slack-corp.com?

You can revoke it once I've figured out what the issue is

**Comment by benzmuircroft** [comment]
sent

**Comment by l12s** [comment]
Ok, so your code snippet works for me. Would you mind trying the following:

Update to the latest version of the client (2.0.4). This requires a package name change, so you'll do `npm install @slack/client --save`

Try the following code:

```js
var RtmClient = require('@slack/client').RtmClient;
var token = 'xoxp-...';
var rtm = new RtmClient(token, {logLevel: 'debug'});
rtm.start();
```

... and let me know what happens?

**Comment by benzmuircroft** [comment]
`[Error: invalid_array_arg] undefined`

**Comment by benzmuircroft** [comment]
`verbose: attempting to connect via the RTM API
debug: { '0': 'connecting' }
verbose: rtm.start successful, attempting to open websocket URL
debug: { '0': 'authenticated',
  '1': 
   { ok: true,
     self: 
      { id: 'U0PB4E1NZ',
        name: 'benzmuircroft',
        prefs: [Object],
        created: 1456586277,
        manual_presence: 'active' },
     team: 
      { id: 'T0PB4ENP5',
        name: 'ytRevshare',
        email_domain: '',
        domain: 'ytrevshare',
        msg_edit_window_mins: -1,
        prefs: [Object],
        icon: [Object],
        over_storage_limit: false,
        plan: '',
        over_integrations_limit: true },
     latest_event_ts: '1456696090.000000',
     channels: [ [Object], [Object], [Object], [Object], [Object] ],
     groups: [],
     ims: [ [Object], [Object], [Object] ],
     cache_ts: 1456696690,
     subteams: { self: [], all: [] },
     dnd: 
      { dnd_enabled: true,
        next_dnd_start_ts: 1456696800,
        next_dnd_end_ts: 1456732800,
        snooze_enabled: false },
     users: [ [Object], [Object], [Object], [Object] ],
     cache_version: 'v13-tiger',
     cache_ts_version: 'v1-cat',
     bots: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     url: 'wss://ms633.slack-msgs.com/websocket/6uKAcpmUqHzzMibFCh5DECECXw4sAJe9s0zekkpdlF_9VB4tFexqyGghE-IeSMiZkCmflUp38iYJVj1Q_amfQgDQ67uymJMNqtUW0ZWUaGdnt7wC1pJZqPPpUPsd1G2Ydx_TMmInfbKKhavESq7_nQ==' } }
debug: { '0': 'ws_opening' }
debug: { '0': 'ws_opened' }
debug: {"type":"hello"}
debug: { '0': 'raw_message', '1': '{"type":"hello"}' }
debug: { '0': 'open' }
debug: {"reply_to":2502,"type":"message","channel":"C0PB8EKV4","user":"U0PB4E1NZ","text":"you","ts":"1456680489.000044"}
debug: { '0': 'raw_message',
  '1': '{"reply_to":2502,"type":"message","channel":"C0PB8EKV4","user":"U0PB4E1NZ","text":"you","ts":"1456680489.000044"}' }
debug: {"type":"reconnect_url","url":"wss://ms633.slack-msgs.com/websocket/bcxC_lyrhs_eu_kJSa5txLJzKisTy-dzVJeVmQ1gaTfGLX6ATEXzzURegmCVhrzxYEQ50pC7p7jOAYcReJp2LUXDQLRnNv6c7qvo68H_jH5vRM0MLEnBys-CsZGBDh8xwXcXmI0N3E0fwIjxODr6TQIF6Ilet84uY9-6zKXMcY0="}
debug: { '0': 'raw_message',
  '1': '{"type":"reconnect_url","url":"wss://ms633.slack-msgs.com/websocket/bcxC_lyrhs_eu_kJSa5txLJzKisTy-dzVJeVmQ1gaTfGLX6ATEXzzURegmCVhrzxYEQ50pC7p7jOAYcReJp2LUXDQLRnNv6c7qvo68H_jH5vRM0MLEnBys-CsZGBDh8xwXcXmI0N3E0fwIjxODr6TQIF6Ilet84uY9-6zKXMcY0="}' }
debug: { '0': 'reconnect_url',
  '1': 
   { type: 'reconnect_url',
     url: 'wss://ms633.slack-msgs.com/websocket/bcxC_lyrhs_eu_kJSa5txLJzKisTy-dzVJeVmQ1gaTfGLX6ATEXzzURegmCVhrzxYEQ50pC7p7jOAYcReJp2LUXDQLRnNv6c7qvo68H_jH5vRM0MLEnBys-CsZGBDh8xwXcXmI0N3E0fwIjxODr6TQIF6Ilet84uY9-6zKXMcY0=' } }
debug: {"type":"presence_change","user":"U0PB4E1NZ","presence":"active"}
debug: { '0': 'raw_message',
  '1': '{"type":"presence_change","user":"U0PB4E1NZ","presence":"active"}' }
debug: { '0': 'presence_change',
  '1': 
   { type: 'presence_change',
     user: 'U0PB4E1NZ',
     presence: 'active' } }
debug: {"type":"ping","id":1}
debug: {"type":"pong","reply_to":1}
debug: { '0': 'raw_message', '1': '{"type":"pong","reply_to":1}' }
debug: {"type":"reconnect_url","url":"wss://ms633.slack-msgs.com/websocket/3CDnlM7LPq2P75lqCi3xZo2fW9xhkX2q6jIMPpusQqTzCMU_GinB5VdnxPjkyKRvXDZ7DcDw9xwKQw-T8rBJOeDLLwIzLiEl1wLMEArGxEWIV7CTkDQ_vrUiGIic5KiooX2TwQl1Awpl8OzzGLEsQDRzDCqrP_kGOXtVcnDxxUM="}
debug: { '0': 'raw_message',
  '1': '{"type":"reconnect_url","url":"wss://ms633.slack-msgs.com/websocket/3CDnlM7LPq2P75lqCi3xZo2fW9xhkX2q6jIMPpusQqTzCMU_GinB5VdnxPjkyKRvXDZ7DcDw9xwKQw-T8rBJOeDLLwIzLiEl1wLMEArGxEWIV7CTkDQ_vrUiGIic5KiooX2TwQl1Awpl8OzzGLEsQDRzDCqrP_kGOXtVcnDxxUM="}' }
debug: { '0': 'reconnect_url',
  '1': 
   { type: 'reconnect_url',
     url: 'wss://ms633.slack-msgs.com/websocket/3CDnlM7LPq2P75lqCi3xZo2fW9xhkX2q6jIMPpusQqTzCMU_GinB5VdnxPjkyKRvXDZ7DcDw9xwKQw-T8rBJOeDLLwIzLiEl1wLMEArGxEWIV7CTkDQ_vrUiGIic5KiooX2TwQl1Awpl8OzzGLEsQDRzDCqrP_kGOXtVcnDxxUM=' } }
debug: {"type":"ping","id":2}
debug: {"type":"pong","reply_to":2}
debug: { '0': 'raw_message', '1': '{"type":"pong","reply_to":2}' }
debug: {"type":"ping","id":3}
debug: {"type":"pong","reply_to":3}
debug: { '0': 'raw_message', '1': '{"type":"pong","reply_to":3}' }`

**Comment by benzmuircroft** [comment]
i'll delete that in a sec

**Comment by benzmuircroft** [comment]
looks like it works

**Comment by l12s** [comment]
Ok, great, glad that worked out. Have fun developing your app!

**Comment by benzmuircroft** [comment]
wow you are cool
