### ISSUE TITLE
Accessing MemoryDataStore

### ISSUE THREAD

**Issue by tnws** [slackhq/node-slack-client#151]
Is there a certain way to access `MemoryDataStore`? I would like to use functions such as `getUserByName`, and others, without storing the user data once more.

**Comment by Everesty** [comment]
Are you trying to access the data store of a RTM client? If so, the client has a `dataStore` field for that.

If you are referring to accessing the MemoryDataStore class, it's exported with the rest of this module; `require('@slack/client').MemoryDataStore`

**Comment by tnws** [comment]
Data store of an RTM client, yeah.

I've tried `require('@slack/client').MemoryDataStore`, however, I'm not seeing where to go from there.

**Comment by l12s** [comment]
Do you want to get the default data store attached to the RTM client or pass in one that you'll create / configure yourself?

**Comment by tnws** [comment]
The default one.

**Comment by Everesty** [comment]
So, the `RtmClient` accepts a `dataStore` option. That option must be a `DataStore` object-- more specifically, it must be a type that inherits the abstract `DataStore` class. So, in our case, `MemoryDataStore`. Additionally, `MemoryDataStore` doesn't take any parameters to construct.

```js
var rtm = new Slack.RtmClient(TOKEN, {
    // If you wanted, you could store the data store in it's own variable. Since the RTM client
    // provides a field for it, I'll going to keep with using that.
    dataStore: new MemoryDataStore()
});
```

From there, using the data store is simple. You can access it via the client's `dataStore` field (or by variable, in the case you chose to do that).

For example, in the case that I wanted to get data about a user whenever they send a message, I'd want to use the `getUserById` method of the `MemoryDataStore`.

```js
rtm.on(RTM_EVENTS.MESSAGE, function(data) {
    var user = rtm.dataStore.getUserById(data.user);
    console.log(user.name + ' said "' + data.text + '"');
});
```

As of writing, I don't believe there are any docs on what methods `MemoryDataStore` contains (though that's being worked on). For now, I'd recommend looking at the source for the object, `/lib/data-store/memory-data-store.js`.

---

@l12s "default data store attached to the RTM client"? The only default data store I see is for the legacy client.

(Also, I just noticed that the jsdoc for the constructor of the RTM client lists `opts.dataStore` twice. I'm a lazy-butt and don't wanna submit a pull request for it.)

**Comment by tnws** [comment]
@Everesty Thank you.

**Comment by l12s** [comment]
@Everesty - good catch, I play around with a version that I've set up with some defaults, so I was getting that mixed up with the actual implementation.

I'll push a change to fix that JSDoc issue momentarily - thanks :)
