### ISSUE TITLE
Using node-slack-client behind proxy

### ISSUE THREAD

**Issue by golcinab** [slackhq/node-slack-client#156]
Support to usage behind proxy solved reported and solved by this issue:
https://github.com/slackhq/node-slack-client/issues/91

has disappeared.
Can you fix-it?

**Comment by l12s** [comment]
You can use the `proxiedRequestTransport` to do this, see https://github.com/slackhq/node-slack-client/blob/master/lib/clients/transports/request.js

An example of doing this is:

```
var rtmClient = new RtmClient(token, { transport: proxiedRequestTransport } );
```
