### ISSUE TITLE
dataStore.getChannelGroupOrDMByID ?

### ISSUE THREAD

**Issue by mvaragnat** [slackhq/node-slack-client#159]
Hi Leah,

Is there a plan to add a convenience method like in the v1 client ?
If desired, I could submit a PR. Let me know!

(same for ChannelOrGroupByName and UserOrBot, I guess)

**Comment by Everesty** [comment]
They do exist! They're methods of the `MemeoryDataStore` object-- more specifically the `SlackDataStore` which is an abstract class used to make data store classes, in which `MemoryDataStore` is the only one that exists currently.

I did write up [an tutorial/example on another issue](151#issuecomment-190514028) a few days ago. If you want to see a list of methods that the `MemoryDataStore` supports, the only option you have is to check [it's source.](https://github.com/slackhq/node-slack-client/blob/master/lib/data-store/memory-data-store.js)

As for the the lack of documentation that caused this issue, it's already been mentioned in the past/other issues that JSDoc should be generated, plus other documentation being needed.

**Comment by mvaragnat** [comment]
Hello Everesty,

Thank you so much, by the way, for the example you gave. I read it some time ago and it allowed my to get started.

Maybe I was not clear enough. I am aware that there are getChannelById and getGroupById methods, but before you had things like getChannelOrGroupOrDMByID, which was a more flexible approach (whichever type of source, you were able to capture the object). I don't think that this method exists anymore. I suggested to recreate it. Is it clearer?

**Comment by Everesty** [comment]
Ah, I see where I went wrong. I forgot to mention that `SlackDataStore` does implement those methods you were looking for:

https://github.com/slackhq/node-slack-client/blob/master/lib/data-store/data-store.js#L338

Sorry about that.

**Comment by mvaragnat** [comment]
Awesome ! I did not see them. Closing the issue, then
