### ISSUE TITLE
Can't seem to delete channel I created

### ISSUE THREAD

**Issue by benzmuircroft** [slackhq/node-slack-client#162]
var cid;

    rtm.on(RTM_EVENTS.CHANNEL_CREATED,function(ev){
        cid=ev.channel.id;                                   //created
        };

     web.channels.create('name_of_channel');

then i want to delete it on the first message it receives...

    rtm.on(RTM_EVENTS.MESSAGE,function(m){
        web.channels.unarchive(m.channel);                   //not deleted
        web.channels.unarchive(cid);                         //not deleted
        });

web.channels.remove and delete don't exist.

How can I delete a channel that this api created?

**Comment by benzmuircroft** [comment]
node-slack-client/lib/clients/web/facets/channels.js

lines 5 - 18 are dead api documentation  links (404 pages)

example: https://api.slack.com/methods/channels.unarchive%7Cchannels.unarchive

**Comment by benzmuircroft** [comment]
I literally want to destroy/obliterate the channel

**Comment by benzmuircroft** [comment]
If the api can create a channel then it should be able to delete it! otherwise my team is stuck having to spend time deleting channels (and hating me for constantly making them have to do a redundant clean up task)

**Comment by benzmuircroft** [comment]
the only thing I can think of is sending in phantomjs to headlessly login as my self and physically delete the channels via navigating through the UI using jquery selectors...

**Comment by l12s** [comment]
Ok:
- the API method you're looking for is [channels.archive](https://api.slack.com/methods/channels.archive) There isn't a way to permanently delete a channel via the API, but you can as a team admin, you can see the docs to do so here: https://get.slack.help/hc/en-us/articles/213185307-Deleting-a-channel
- the link you were running into is in JSDoc format, which means you need to take the part to the left of the pipe character | The part after the pipe character is how the link will display when JSDoc is rendered
- unarchive is the opposite of archiving; it would restore a channel that you've archived back to being usable again

**Comment by nitintt1991** [comment]
Hey I have the same problem. I created one channel and now I would no longer need it.
I went through this link [https://get.slack.help/hc/en-us/articles/213185307-Delete-a-channel](url)
but it's of no help, the reason being I can only find two options in additional settings of the channel, one being edit name and other being edit channel purpose.
Please note the channel has been created by me.
Could anyone please help on this?

**Comment by aoberoi** [comment]
you must be a team owner or admin to delete a channel. you should still be able to archive the channel.

**Comment by AkiTensai** [comment]
As the "Primary Owner", I can't delete the channel that was originally #general. I have since renamed it to something else, have a new #general, and don't see an option to promote a new channel to the undeletable general channel. The help article doesn't state that #general is not delete-able.
