### ISSUE TITLE
17 concurrent connection limit to Slack using the same API key (same bot)?

### ISSUE THREAD

**Issue by ernestgwilsonii** [slackhq/node-slack-client#166]
We use the Hubot Slack integration on Node.js and we are running into an issue that may be a limitation of the Slack API and/or the node-slack-client.
We use a single Hubot API key that allows our bot to connect as the same user from multiple locations.
We are careful not to flood or spam any channels, our users interact we if our single bot making it convenient for them two only communicate with a single bot user.
As we bring up new locations, we spin up a connection using that same Hubot API key from each data center.
We carefully ensure that unique data center commands are only responded to by the correct bot.
Today we ran into an issue that we are easily able to reproduce repeatedly, it seems that we are only able to make 17 connections.
When we bring up the 18th connection we are unable to connect.
Any 17 datacenters are able to connect, but the 18th connection, no matter which data center is unable to connect.
We are wondering if there is a configuration setting that can be changed or if they see is a known limit.
Is there a 17 concurrent connection limit?
Is there a parameter within the node-slack-client that can or must be changed?

**Comment by l12s** [comment]
Which version of the client are you using?

I'll check in with the folks who maintain our RTM API about whether there's a flat connection limit too.

**Comment by ernestgwilsonii** [comment]
Hi, looking at package.json I see:
hubot-slack 3.4.2
slack-client 1.4.0
I thought this calls node-slack-client, maybe it only relies on slack-client, not sure?

Please let me know after you speak with the folks who maintain our RTM API about whether there's a flat connection limit too, that would hurt.

**Comment by l12s** [comment]
Hi there, so you should only be able to create 16 connections from the same API token. Unfortunately, that's a general limit across all of Slack's RTM APIs - I'd suggest reaching out via Slack's general support channels if you want to ask about an exception to that.
