### ISSUE TITLE
RTM_EVENTS.MESSAGE never fires

### ISSUE THREAD

**Issue by jph98** [slackhq/node-slack-client#171]
The following event never fires for me on sending of a message to a channel, however reactions and other events do fire.  Am I missing something?

```
var RtmClient = require('@slack/client').RtmClient;
var RTM_EVENTS = require('@slack/client').RTM_EVENTS;
var CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS;
var RTM_CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS.RTM;

// See: https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js
var rtm = new RtmClient(SLACK_TOKEN, {logLevel: 'debug'});

console.log("\nClient connected: " + rtm.connected + "\n");
rtm.start();

rtm.on(RTM_EVENTS.MESSAGE, function handleMessage(message) {
      console.log("\nMessage Received", message);
      process.exit();
});

```

**Comment by PaulAsjes** [comment]
Two things:

- To detect whether you've connected you need to use the `CLIENT_EVENTS.RTM.RTM_CONNECTION_OPENED` event:
```
rtm.on(CLIENT_EVENTS.RTM.RTM_CONNECTION_OPENED, () => {
 console.log('Connected!');
});
```
- Is your bot in the channel that you're sending messages to? The `MESSAGE` event will only trigger when a message is sent in a channel the bot resides in.

**Comment by suresh1271** [comment]
@PaulAsjes can't we send message to User by User Id ot IM Channel Id ? Please help me in this

rtm.on(CLIENT_EVENTS.RTM.RTM_CONNECTION_OPENED, function () {
	  rtm.send( 'message','D6KNFR329',function (err, res) {
console.log("error : "+err);
console.log("response : "+res);
});
});

//D6KNFR329 IM channel id
I user the above code but i didn't get any message. If I replace the IM channel id with normal channel ID(#general) I'm able to receive. But i want to send to an user please help me in this
