### ISSUE TITLE
Cannot Send Anything with Attachments

### ISSUE THREAD

**Issue by jadesym** [slackhq/node-slack-client#172]
I am able to send messages to a slack channel fine, but whenever I try to send a message with attachments, the messages never seem to enter my slack channel:

`webClient.chat.postMessage(channelId, msg, data, callback);`

Data like the following works:

`const data = {username: 'braintreebot', as_user: true, attachments: [{}]};`

But data like this doesn't:

`const data = {username: 'braintreebot', as_user: true, attachments: [{"pretext": "pre-hello", "text": "text-world"}]};`

I've tried a wide variety of different combinations, but it seems like I can't get any of the fields, colors, or fallbacks to work either.

Additionally, I've tried to use the callback and pass in a function (cause I thought the callback was supposed to pass errors, responses back), but I was unable to get any valuable debug information. Furthermore, I tried to get the object returned from the call as well, and that was undefined.

**Comment by hadios** [comment]
Hi @jadesym,

Had the same problem. Stringify the array seems to solve it.

`const data = {username: 'braintreebot', as_user: true, attachments: JSON.stringify[{}]}`

Took me hours to figure this out. Not sure if this is the intended way of passing the attachment. Hope that helps.

**Comment by jadesym** [comment]
Oh wow, thank you! That fixed my problem completely!
