### ISSUE TITLE
Client 2 - Ready for production?

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#181]
Hey there,
I have been working with two branches in parallel for the past 3 months testing and adapting the beta version of the new client to my code.

My question is: I have a system with almost 1000 bots and I want to migrate it to new client. Do you guys feel like it is already ready for production? Or maybe it is still needing more testing?

Thank you!

**Comment by l12s** [comment]
Sorry about the slow reply, things have been super busy recently.

So, we have some folks using the new version of the client in production currently. I believe @acemtp at Talkus is doing so and may be able to give you some additional info.

My general feeling is that it should be ready to use at scale, but that it's ultimately your call on if it's suited for what your system is doing. That said, I'd really like to get more folks using this, so if you do go live with it, I'll try and be as responsive as I can be for any issues you see.

**Comment by acemtp** [comment]
Hello @brunosiqueira,

We use the 2.0 version in production on Talkus http://talkus.io for a few months and it's more stable than the 1.5 version.

You should not have issues (but we never try with 1000 bots).

**Comment by rdlh** [comment]
Hey @brunosiqueira,

I don't know if that's still a current question, but:

We're using the [2.3.0 version](https://github.com/slackhq/node-slack-client/tree/2.3.0) here at [Slaask](https://slaask.com) with **several thousands** of bots and everything is working like a charm. We're using node clustering (with [pm2](http://pm2.keymetrics.io)) to scale our bot user growth and that's really stabler than 1.5.

Contact me at remi@slaask.com if you've got any questions about that scale.
