### ISSUE TITLE
Slack on osx does not recognise proxy settings

### ISSUE THREAD

**Issue by fabriziopandini** [slackhq/node-slack-client#185]
I'm using Slack on osx behind corporate proxy, and corporate proxy require credentials.

Slack has problems in retrieving proxy credentials from Network Preferences (where credentials are configured)

Is there a way to : 
1) make slack read proxy credentials
2) give proxy credentials directly in slack 
3) explicitly set proxy and proxy credentials for slack ( +1 for me on this option)

**Comment by Everesty** [comment]
Quick question, are you reporting an issue about the official Slack client (the one you get from [Slack's download page](https://slack.com/downloads)) or are you reporting an issue about the module that this repository hosts? The two are, indeed, different and the official Slack client (last I checked) doesn't run on this module.

If you're reporting an issue for the official Slack client, then you're in the wrong place. Instead, [send a ticket](https://slack.com/help/contact) to one of the lovelies at Slack Support.

If you're having an issue with the client, then you'll have to use the proxy transport located in `/lib/clients/transport/request.js`.

```
var proxiedRequestTransport = require('@slack/client/lib/clients/transports/request').proxiedRequestTransport;

// Supply the transport as an option to your client
new someKindOfClient(token, {
    transport: proxiedRequestTransport
});
```

**Comment by fabriziopandini** [comment]
Thanks! I will contact slack support.
I will close the issue
