### ISSUE TITLE
Doesn't pass proxy url to RTMClient

### ISSUE THREAD

**Issue by tomoyukim** [slackhq/node-slack-client#189]
Hi!
I'm using slack-client behind corporate proxy and intend to update the version. I cannot pass proxy url to RTMClient however. WebSocket itself has proxyUrl as option argument but wrapper client doesn't.
Do you have a plan to fix it ?

**Comment by Everesty** [comment]
Proxy support is there for the RTM client, it's just a little different.

The RTM client uses objects called "transports" to send requests given certain information. The transport classes can be found in the `lib/clients/transports/` directory of this repository.

The RTM client accepts a `socketFn` transport option and the `BaseAPIClient` instance that the RTM client inherits accepts a `transport` option. The `socketFn` option handles opening a socket for the RTM api and the `transport` option handles the call to the rtm.start slack api method (in the case of a rtm client).

There is only one transport for sockets (unless you make your own): `@slack/client/lib/clients/transports/ws.js` which returns a `wsTransport` function. The `wsTransport` function accepts a `proxyURL` option (just like you stated in the issue :D). The issue with this is that you can't really use the two options together as the RTM client only supplies a socket url to the `socketFn`.

An easy workaround to the above is to supply a `socketFn` that passes it's first parameter to `wsTransport` and appends it's own proxyURL option:

```js
var wsTransport = require('@slack/client/lib/clients/transports/ws');
new RTMClient(token, {
    socketFn: function(socketUrl) {
        return wsTransport(socketUrl, {
            proxyURL: yourProxyUrl,
            // there's a mistake in transport/ws.js that tries to use both "proxyURL" and "proxyUrl"
            // so just submit both options for now as a temporary workaround.
            proxyUrl: yourProxyUrl
        });
    }
});
```

@l12s Might wanna fix that to be a little easier? Also, in `transports/ws.js`, the function attempt to use **both `proxyURL` and `proxyUrl`.** Definitely needs to be fixed.

As for applying a proxy to get the rtm.start method call to work, the process is a ton easier; just use a `proxiedRequestTransport`:

```js
new RTMClient(token, {
    transport: require('@slack/client/lib/clients/transports/request.js').proxiedRequestTransport(yourProxyUrl)
});
```

**Comment by tomoyukim** [comment]
Thank you!
I can pass my proxy url.

**Comment by davidkarlsen** [comment]
Could this be done easier by picking up https_proxy from the environment?
