### ISSUE TITLE
Cannot install @slack/client through npm

### ISSUE THREAD

**Issue by ddelnano** [slackhq/node-slack-client#192]
In the README it explicitly says that you should install the package @slack/client instead of slack-client.  However, that does not work.  I get permission denied public key when attempting to install the former.

**Comment by l12s** [comment]
Hi there, I tried `npm install @slack/client` on a fresh laptop (no login to NPM, no slack creds) and it installed ok for me.

Mind retrying?

**Comment by ddelnano** [comment]
Yea it seemed to install fine this time.  I used a different laptop so maybe that had something to do with it?

**Comment by ddelnano** [comment]
You didn't change anything with the package?

**Comment by Everesty** [comment]
Are you positive that you didn't accidentally try to install `slack/client`, which points to a github repository that doesn't exist? When trying to install `slack/client`, I got the same "Permission denied (publickey)." issue.

**Comment by ddelnano** [comment]
Yea I guess it's possible. Well since this is clearly not an issue in closing this.

**Comment by wittnl** [comment]
For anyone that also happens to come across this problem, I found that just a minor version difference (3.9.x/3.10.x) caused `npm install` to fail with an unhelpful message "Invalid package name"

Updating npm did the trick `npm i npm -g`

**Comment by HienNguyen711** [comment]
@wittnl : thanks I tried your solution and it worked!
