### ISSUE TITLE
High memory usage - crashing my mac, fails to shutdown

### ISSUE THREAD

**Issue by kristapselsins** [slackhq/node-slack-client#207]
![screenshot 2016-05-05 14 31 26](https://cloud.githubusercontent.com/assets/6965479/15042598/12ea3546-12ce-11e6-9490-72b7ef9577b3.png)

**Comment by l12s** [comment]
Hi there, this repo is for the Node slack client, which is a library that allows you to connect to Slack's APIs in Node.

I'd suggest checking out our (Help Center)[https://get.slack.help/hc/en-us] to get help on the mac client.
