### ISSUE TITLE
can bots not join channels?

### ISSUE THREAD

**Issue by freder** [slackhq/node-slack-client#26]
hi,

I just started writing a bot that joins and listens on all my team's channels. however, according to https://api.slack.com/bot-users there doesn't seem to be an option for bots to join channels (other than #general). — or am I missing s.th. here?

freder

**Comment by evansolomon** [comment]
Bot users need to be invited to channels.  If you say `@yourbotusername` you will get a dialog to invite him/her/it.

**Comment by jtatum** [comment]
The list of methods available to bot users is at the bottom of: https://api.slack.com/bot-users. Not sure why channel.join is prohibited to bots...

**Comment by paulhammond** [comment]
No, bots cannot join channels by themselves. This is something we're talking about changing in the future but we have no firm plans yet.

We're tracking that as a bug inside Slack, so I'm going to close this out here. We'll make an announcement on [the SlackAPI twitter account](twitter.com/slackapi) if this situation changes...

**Comment by buley** [comment]
I seemingly cannot post so-called complex messages as a bot user. 

I'd love to be able to have a bot user call a slash command. I'm not sure if this is possible with so-called complex messages, but I ran into errors while trying.

The [bot docs](https://api.slack.com/bot-users) say (with original bolding):

> To post more complex messages as a bot user, clients can use the Web API methodchat.postMessage. **Be sure and set as_user to true** and use your bot user token.

And yet when I set this field:

> { ok: false, error: 'not_in_channel' }

When I try to join the channel:

> { ok: false, error: 'user_is_bot' }

**Comment by kristg** [comment]
Is adding bots to individual channels still not supported? The bot I integrated sends messages to "slackbot" only. Inviting the bot as you'd invite members does not seem to work.

**Comment by hpg-mheck** [comment]
Sad that this is not supported while coding for the Global Legal Hackathon, 2018, in Chicago.

**Comment by jtatum** [comment]
One could argue that it's part of the slack security model. Because bots may not be trusted (e.g. a third party app), allowing them to join any channel (even public) and read history is not desirable.

**Comment by AashrithChilkepalli** [comment]
> Bot users need to be invited to channels. If you say `@yourbotusername` you will get a dialog to invite him/her/it.

I wanted to ask how do i disable the bot being added to channels . Is this possible ? Also is there a way i can edit the dialog that comes up when i say @botusername . Thanks! @evansolomon

**Comment by aoberoi** [comment]
@AashrithChilkepalli nope, unfortunately you cannot prevent the bot from joining a channel programmatically. this is something we're aware of as something users need, but we don't have a built in solution for this yet.

i have a workaround suggestion: you can make your bot completely non-functional in channels it doesn't recognize. in addition, when it joins a channel it shouldn't be in, you can post a message telling the channel that it won't work there and asking a human user to please `/kick` itself so that it can leave.

**Comment by alper** [comment]
This restriction is supposedly lifted, but if I call the `conversations.join` method using a bot token, I get:

```
{
    "ok": false,
    "error": "not_allowed_token_type"
}
```

**Comment by ejazalimadni1** [comment]
@alper 
{
    "ok": false,
    "error": "not_allowed_token_type"
}

do not use xoxp-xxxxxxxxxxx-x-xx-xx token
 use xoxb-xxxx-x-x--x-x-x-x 

after that when you will receive activity notification in Slack app add your bot/app  to specific chenel  where you want to auto reply 

![slack_add_bot_to_chanel](https://user-images.githubusercontent.com/40489691/78990956-3762a300-7b51-11ea-95c9-ce30f89a2fb6.png)

**Comment by pfolk** [comment]
@alper Did you mean that the "bots can't join channels using conversation.join" restriction is lifted?  If so can you point me to where you found that info?  It's not working for me, but the message I get is that the bot is already in the channel, which is not right =)

**Comment by ro31337** [comment]
This needs to be implemented.

**Comment by FunkyloverOne** [comment]
It is now implemented! See this: https://api.slack.com/methods/conversations.join

**Comment by mmobin789** [comment]
@FunkyloverOne no it's not check the errors tab below on above link.

is_bot : This method cannot be called by a bot user.

**Comment by prateekjain98** [comment]
> @FunkyloverOne no it's not check the errors tab below on above link.
> 
> is_bot : This method cannot be called by a bot user.

It's working for me. I'm using bolt app and added [channels:join](https://api.slack.com/scopes/channels:join) in the Bot token scopes. After that, if you called this method, it'll add your bot to the public channel

**Comment by RovoMe** [comment]
> It's working for me. I'm using bolt app and added [channels:join](https://api.slack.com/scopes/channels:join) in the Bot token scopes. After that, when I called this method, it added the bot to the public channel

But `channels:join` is deprecated and therefore shouldn't be used further.

In our setup we have an external admin tool that basically manages all the users, groups and channels an propagates changes to Slack. While the bot is automatically a member of the channel when we create the channel via the API, for channels that existed before the bot is not automatically added and adding it via `conversations.invite` fails with a given error of `null` when the bot token is used. If we switch the token from the bot one to the user token who installed the bot in the workspace, then the invitation of the bot to the channel succeeds regardless if that user is a member of that particular channel or not (of course assuming proper scope and permission settings)
