### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by khanh-nguyen** [slackhq/node-slack-client#39]
My bot often crashes for the following error:
```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Stopping process with SIGKILL
State changed from starting to crashed
State changed from crashed to starting
Process exited with status 137
```
Is it a bug within `node-slack-client` or some settings with heroku that I'm missing? 
According to this [StackOverflow thread](http://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of), you can fix it by telling your app to listen to a port that Heroku assign dynamically `app.listen(process.env.PORT)`. But how can you do it with `slack-client`? 

My code is [here](https://github.com/khanh-nguyen/node-slackbot).

**Comment by khanh-nguyen** [comment]
I got it working. Turn out it must be an `app`.

**Comment by shyshy** [comment]
Hey @khanh-nguyen, does this still resolve the issue for you? I tried changing my Procfile and I still get the error.

**Comment by Carpetfizz** [comment]
Hey @khanh-nguyen did you resolve your issue by simply creating an `app` and not using it, or does the `node-slack-client` somehow integrate with it? Thanks.

**Comment by iostreamer-X** [comment]
Had the exact issue with my bot on heroku. I just added a server that heroku could bind to and it worked perfectly.

```javascript
http = require 'http'
handle = (req, res) -> res.end "hit"

server = http.createServer handle

server.listen process.env.PORT || 5000
```

**Comment by lhelminiak** [comment]
What file did you add this code to?

**Comment by aoberoi** [comment]
@lhelminiak you would add this to your main file, which be default is `index.js`, but in your app might be `server.js` or `app.js`.
