### ISSUE TITLE
Cannot listen on `team_join` event

### ISSUE THREAD

**Issue by khanh-nguyen** [slackhq/node-slack-client#40]
I want to set `slack` client to listen on [`team_join` event](https://api.slack.com/events/team_join).
```
slack.on('team_join', function(message) {
    var user = slack.getUserByID(message.user),
        channel = slack.getChannelByName('general');
    
    console.log('message:', message);
    channel.send('Hello ' + user.name);
});
```
However, nothing happens when a new member joins the team.

**Comment by khanh-nguyen** [comment]
ugh, changing event name or combining events together without document is not fun :(

**Comment by jschuur** [comment]
@khanh-nguyen I ran into this exact same problem yesterday. Were you able to solve it? I there a new naming convention for events?

**Comment by khanh-nguyen** [comment]
Yeap, @jschuur, as you've seen in my code, they combined `team_join` and `user_change` into `user_change`. I don't know how different it is to use "hubot powered Slack bot" but if you want to another eye on your code, let me know.
