### ISSUE TITLE
Not published on npm

### ISSUE THREAD

**Issue by jkresner** [slackhq/node-slack-client#44]

**Comment by ekmartin** [comment]
It's published under the name [slack-client](https://www.npmjs.com/package/slack-client).

**Comment by jkresner** [comment]
Perhaps mention in the readme. Or rename the repo. There are so many node-slack, slack-node alternatives could help!

**Comment by keoghpe** [comment]
+1

**Comment by l12s** [comment]
I've merged in #52 which should clarify this. Thanks for your patience!

**Comment by vanm** [comment]
Thanks @l12s!
