### ISSUE TITLE
fetchHistory returns true

### ISSUE THREAD

**Issue by 97-109-107** [slackhq/node-slack-client#46]
*Disclaimer: I'm not familiar with coffescript, in order to read the source I had to compile ``channel.coffee`` to javascript. Here is the JS file I'm interpeting this from: http://sprunge.us/GRSP*

I'm hoping to be able to load a channel's history, however, I don't see any history appearing in the console (I believe this is the current behavior), nor being returned by the function, when I use:

````
  var h = slackChannel.fetchHistory();

  console.log(h);
````

From what I understand, underneath the hood, after the parameters of fetchHistory are interpreted the client performs an appropriate `_apiCall`.  It populates the api call's with the proper command based on where the bot is (``channels.history or groups.history or im.history``) and optional range params. Then we have the callback which is supposed to return the history call's ``data`` to ``return this._client.logger.debug(data)``

Am I'm misinterpreting something or is the function incomplete?

**Comment by brandonhorst** [comment]
+1

Is this possible?

**Comment by 97-109-107** [comment]
@brandonhorst I don't remember how exactly I solved this issue, but a quick search on the codebas suggest that I haven't used fetchHistory in the end. I could however see that I must've moved the history fetching aspect to be a request made on the api directly, by hand. Hope this helps.

**Comment by brandonhorst** [comment]
Yeah, I ended up doing the same. Thanks!
