### ISSUE TITLE
Event naming conventions are inconsistent.

### ISSUE THREAD

**Issue by elvinyung** [slackhq/node-slack-client#50]
Being pedantic.

So events like `loggedIn` and `presenceChange` are emitted as camelCase, but `star_added` and `star_removed` (and `raw_message`, but I'm not sure if that's intended to be actually exposed) are in snake_case.

For reasons related to preserving my sanity, can I submit a PR that either changes the snake_case events to be emitted as camelCase, or (for API preservation) emitted as both snake_case and camelCase? (Or variations thereof.)

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also includes standardized event names as well as object refs to allow you to use them. They're documented in https://github.com/slackhq/node-slack-client/tree/master/lib/clients/events

So, I'd suggest that the best way to resolve this issues is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.
