### ISSUE TITLE
does this support the rest/webhooks APIs or just realtime?

### ISSUE THREAD

**Issue by dcsan** [slackhq/node-slack-client#62]
given theres no docs or examples apart from the realtime `slack.on ` xxx i:m assuming no?

**Comment by izeau** [comment]
I don’t know if it’s safe to use (tbh this whole lib looks like an early WIP – which is a good thing), but there's an internally used method to communicate using the REST API: [`Client#_apiCall`](https://github.com/slackhq/node-slack-client/blob/deee924ac534d4a6a2201321a989989c945c75a9/src/client.coffee#L534).

```
var Slack = require('slack-client');
var slack = new Slack(token);

slack._apiCall('channels.join', { name: 'general' }, callback);
```

Please note that your token is added automatically and you should not set it in the params.
Also the callback does not follow Node convention and the first parameter includes a property `ok` which you should rely on for error handling.

Cheers

**Comment by kurisubrooks** [comment]
This is exactly what I needed, thank you so much @izeau. 
I wish they would add some Documentation... It's very needed.
