### ISSUE TITLE
How does getChannelGroupOrDMByID work? or does it?

### ISSUE THREAD

**Issue by kylepaulsen** [slackhq/node-slack-client#68]
I've been trying to send a DM to a user in a slack channel with many many users connected (at least 100). I've noticed that the IM list is very short (from the object returned from rtm.start) and that the user I'm trying to send a DM to isn't in this list. Normally, you would just look for the DM id using the IM list. How does node-slack-client handle this, if it even can? What's the correct way to send a DM to someone if they are not in the IM list (or how do you get the DM id from a user id)?

**Comment by kylepaulsen** [comment]
Well I figured out an answer... not sure if it is the correct one. I just ended up calling the im.open slack api method. That returns a json response with the channel id (or in this case the user's DM id). Then I can send a direct message with that.

**Comment by MForMarlon** [comment]
If you know the `userId`:
```
slack.openDM(userId, function(openDmData) {
    if (openDmData.ok) {
        var dmChannel = slack.getChannelGroupOrDMByID(openDmData.channel.id);
        dmChannel.send('blah blah blah');
    }
});
```
