### ISSUE TITLE
unable to send a url with <url|Click on this> formatting from my bot

### ISSUE THREAD

**Issue by pvenkatakrishnan** [slackhq/node-slack-client#69]
I am using the slack client for my bot and i am trying to send a formatted message with a url as

```javascript
var content = hello, <www.google.com|Click here> to do some awesome search. 
channel.send(content)
```

I am expecting to see,
`Click here to do some awesome search ` with Click here hyper linked.
But this is not working.
Help ?

**Comment by pvenkatakrishnan** [comment]
Referred the https://api.slack.com/docs/formatting for formatting. Also i tried escaping the < and > characters and still doesnt work.

**Comment by CaptainPalapa** [comment]
Verified also with:
`channel.send('This is a <https://www.google.com|link> test sample.')`

Sent the text to the chat window just like it appears in code.

**Comment by tnws** [comment]
If you use an [attachment](https://api.slack.com/docs/attachments) and `text` within the attachment it'll work out. The only issue with it is that it'll give you the grey bar on the left denoting that it's an attachment.
![show](http://i.imgur.com/vaJDNm9.png)

Or you could try it as `pretext` in an attachment, but there'll be an empty line underneath.

![show](http://i.imgur.com/pNHglAr.png)

To send messages, make sure you use `postMessage`. Let me know if there's a way that I can help.

**Comment by pvenkatakrishnan** [comment]
can you post the actual text that you are passing within the attachment. even after doing as an attachment i am not able to achieve the above effect.

**Comment by pvenkatakrishnan** [comment]
figured out, just need to add user name and set `as_user:true` in the payload

**Comment by tnws** [comment]
My bad, I should've said that as well. Was just about to post the snippet as you figured it out haha
