### ISSUE TITLE
@bots isn't populated on login

### ISSUE THREAD

**Issue by kballard** [slackhq/node-slack-client#7]
When connecting to the service, `@bots` isn't populated in `_onLogin`. It's only ever modified when bots are added/changed.

**Comment by guiceolin** [comment]
hey guys! just submitted a patch for this: #43

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue and that we didn't respond to the PR you submitted, less than :100: on our part

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also caches information on bots to the [data store implementation](https://github.com/slackhq/node-slack-client/tree/master/lib/data-store).

So, I'd suggest that the best way to resolve these issues is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.
