### ISSUE TITLE
Only Listen to a specific channel

### ISSUE THREAD

**Issue by udayms** [slackhq/node-slack-client#72]
Hi,

I wonder if there is any way to listen to messages on a specific channel? Listening to messages event means checking every message that comes into the system and then checking the channel and then performing an action. Isn't there a simpler way in RTM where the bot opens a channel and listens for messages. When the task is complete, it closes the channel.

My real-world usecase is : 
My bot will open a DM channel with a specific user and ask a question. When the user responds, it will followup with a second question. When the user answers that, the bot will thank the user and end the conversation.

**Comment by ghostsquad** [comment]
listen to all messages, and your first line can check which channel that message is coming from. This would essentially be the same code that would be implemented in here.

```
if message.channel.name == 'my_channel'
   # do stuff
```

**Comment by l12s** [comment]
@ghostsquad - thanks for answering this!
