### ISSUE TITLE
Export models

### ISSUE THREAD

**Issue by ghostsquad** [slackhq/node-slack-client#74]
I am unable to stub the models (such as `message`) returned by the various methods of the slack client here because those models cannot be imported. 

Please expose the models used here so I can properly mock this library.

**Comment by l12s** [comment]
Would you mind giving me an example of what you'd like to do here? I don't quite understand why you can't do something like:

```js

var Team = require('./src/team');

```

... so I'm guessing I'm missing something in what you're trying to do?

**Comment by ghostsquad** [comment]
you mean like `require('./node_modules/slack-client/src/team')` I suppose I could do that, but this makes the test a bit brittle. This file is technically considered a "private" module, because it doesn't get exported. If it were to ever be moved/replaced, my tests would break. I suppose I could do that, but I think it's not a good practice to refer directly to src files.

**Comment by l12s** [comment]
You should be able to do ```require('slack-client/src/group');``` I believe.

I recognize it's not ideal and the general structure of the client is something we'll be looking into more going forwards. As part of that I'll define a clearer top level contract for what the module offers that can define a clearer way of doing this.

**Comment by l12s** [comment]
Closing this one for now - I'll drop you an update once we have a plan in place for how to work with this longer term.
