### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by ptarjan** [slackhq/node-slack-client#75]
I sometimes get this firing in my app:

```
Error: stream.push() after EOF
```

I have a listener:

```
slack.on('error', function(error) {
  console.error('Error: ', error);
});
```

but if I look in a debugger, there isn't a listener to the error event on the `EventEmitter`.

![image](https://cloud.githubusercontent.com/assets/40143/10350444/e6e01752-6cf8-11e5-88d4-26f3786f85fc.png)

This is coming from the `rtm.start` operation's `onreadystatechange`

![image](https://cloud.githubusercontent.com/assets/40143/10350482/12fdb95c-6cf9-11e5-955d-be1368691710.png)

**Comment by l12s** [comment]
Hey there, hope you're doing well.

Sorry for the fact we totally ignored this issue :(

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

The [`handleWsError`](https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js#L435) function on the new RTM client should now pass that error through for you.

**Comment by ptarjan** [comment]
No worries. And nice meeting you the other day Leah.
