### ISSUE TITLE
Stache - Docs and Snippets for Slack

### ISSUE THREAD

**Issue by harryward** [slackhq/node-slack-client#81]
Hey all wanted to drop a note and ask you to checkout Stache - its a cool way to create, manage and collaborate on snippets and documentation dynamic to your slack team (and even share version of your documentation or snippet with someone outside of your slack team).

http://stached.io
<a href="http://stached.io"><img src="https://s3.amazonaws.com/f.cl.ly/items/313x1j0T1E3V0k3U4132/Screen%20Shot%202015-10-19%20at%2011.00.11%20AM.png"></a>

example of a public Stache:
http://stached.io/standalone/5Z4xSNrRYfERz29oN

Let me know your thoughts

**Comment by l12s** [comment]
Thanks! I'll pass that on to the folks who work on docs in our DevRel team to check out.
