### ISSUE TITLE
Custom Log Handlers

### ISSUE THREAD

**Issue by njakob** [slackhq/node-slack-client#83]
Would it be possible to expose logging rather than having the client handling it itself ? Currently, I have to simply turn it off through the `SLACK_LOG_LEVEL` env variable.

**Comment by evansolomon** [comment]
You could do something like this as long as your logger conforms to the same (normal?) logging interface with info/debug/error/etc methods.

```js
var client = new Slack(...)
client.logger = yourOwnLogger
client.login()
```

Manually messing with instance variables like that probably isn't the greatest thing in the world, so maybe something like `client.setLogger()` or an argument in the constructor would be a little nicer. But it should be possible currently.

**Comment by l12s** [comment]
Thanks - that's a great fix for now. We're looking into doing some re-design work on the client and I'll ensure that getting a better logging setup gets wrapped into the feature bucket for that

**Comment by njakob** [comment]
Having a method to change the logger is indeed a better solution while changing the instance variable is a nice temporary hack. In case this feature is added to the client, would be just necessary to clearly define the logging interface since there is multiple standards for the methods names (error vs. err, warn ing vs. warn).

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also allows you to pass in your own logger function when you construct a client, for example:

```

var RtmClient = require('slack-client').RtmClient;

var token = process.env.SLACK_API_TOKEN || '';

var rtm = new RtmClient(token, { logLevel: 'debug', logger: function() {} });
rtm.start();

rtm.on('message', function handleRtmMessage(message) {
  console.log(message);
});

```

So, I'd suggest that the best way to resolve these issues is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.
