### ISSUE TITLE
Error: getaddrinfo ENOTFOUND ms410.slack-msgs.com ms410.slack-msgs.com:443

### ISSUE THREAD

**Issue by RafaelCosman** [slackhq/node-slack-client#87]
I get the above error when I run simple_reverse.js with my token.

Is everyone else having this same issue? It started this morning. I'm pretty sure the very same code didn't have an issue last night.

**Comment by RafaelCosman** [comment]
Uh oh, this seems to be a heisenbug -- I just took a break for an hour, came back, didn't change anything and then *it ran just fine*. Now I'm scared :fearful:

**Comment by paulcbetts** [comment]
ms410 in particular had some Difficulties™ that weren't related to your code, sorry about that!
