### ISSUE TITLE
Is this repo in maintenance mode or deprecated? 

### ISSUE THREAD

**Issue by ChrisCinelli** [slackhq/node-slack-client#88]
I do not see a lot of activity. 

The change log is untouched since February. 

The README encourage to contribute with pull requests but there are 19 open and some of them have no feedback.
I see a few pull requests that seems pretty safe to merge:
 * #77 
 * #64 
 * #61
 * #59 
 * #57 
 * #54
 * #48  
 * #43
 * #42 

One that seem particularly important for me is that the client cannot be used in node 0.12 or 4.x  because the `ws` module does not compile. It seems that upgrading ws as specified in #47 will fix the problem.

There is also #56 that rebased #22 so it could be merged but because it was not merged promptly, now it needs again some work to be merged.

 #66 seems also a good candidate to be merged

On active repositories, PR are either rejected with an explanation or merged. So, is this an obsolete repo? Is a new version of the slack node client about to be released?

**Comment by vanm** [comment]
Thanks for bumping this.  I reviewed the PRs I created and rebased the ones that need it.  They are good to go:

#47 - Bump WS to latest
#48 - Remove a no-op
#54 - Handle team migration started
#61 - Basic pass through of error code and message
#66 - Fix reconnect / pong issues

**Comment by l12s** [comment]
Hi there,

Sorry about the delayed response.

We're actively working on improving our support for the opensource clients for the Slack API - we've recently added some really great folks to our DevRel and platform teams who are going to help push these forwards.

For node-slack there's a couple things going on:
- I've refactored the existing client to bring it up to a point where it's easier to use, easier to maintain and easier to contribute to. You can see that work in my own repo here: https://github.com/l12s/node-slack-client. I'll be posting a note to this repo in the next couple days inviting folks to beta test the new client. It has major breaking changes, so it'll be released as a 2.0.0 release and under a new package name. My post to this repo's README will cover the reasoning behind that in more detail
- I'm going to take a look at @vanm PRs above later today and see which of them I can quickly incorporate to spin a 1.5.0 release out to get you some short-term improvements while the 2.0.0 version is in beta

We know that the current progress on our open source clients isn't where it should be and really appreciate everyone who's using them to build cool apps and integrations. Thanks for your patience while we get organized around supporting them better and figuring out how to push them forwards faster and with fuller community involvement.

Leah

**Comment by vanm** [comment]
:+1: thanks, Leah.  Excited to beta test the new client when it's ready.

**Comment by l12s** [comment]
Ok, I've merged in #47, #48, #54 and #61

I'm going to update the changelog later today and update the package to a 1.5.0 version and push that to npm. My intention is that we then pause work on this version of the client while I wrap up the last couple of event handlers for the 2.0.0 version and get eyes on that code + some sample implementations written  for it to root out some of the bugs.

**Comment by l12s** [comment]
Ok, 1.5.0 update is prepped and should be on npm shortly.

**Comment by brunosiqueira** [comment]
Hey @l12s ! How is the evolution to the 1.5.0 going? Curious to start using it!

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.
