### ISSUE TITLE
Takes over `this` context

### ISSUE THREAD

**Issue by martindale** [slackhq/node-slack-client#92]
It seems that when the client is used inside of another constructor, it takes over the `this` context.  Why, I'm not sure, nor how.  Extremely inconvenient.

**Comment by evansolomon** [comment]
Can you give an example?

**Comment by martindale** [comment]
From [snarl](https://github.com/martindale/snarl):
```js
var Slack = require('slack-client');

function Snarl(config) {
  this.token = config.slack.token;
}

Snarl.prototype.start = function() {
  var self = this;
  var slack = new Slack(self.token, true, true);
}

Snarl.prototype.testContext = function() {
  console.log(this); // logs out a Slack client instance
}
```

**Comment by l12s** [comment]
That doesn't return the Slack client context for me, instead giving:

```
> snarl.testContext();
{ token: 'xoxp-xxx-xxx-xxx-xxx' }
```

What version of the client are you running?

**Comment by martindale** [comment]
You're right, I'm testing that locally and not getting the same issue.  I just upgraded to 1.5.  In snarl, I've worked around this, so I'm tracing back to the problem I was having last night.  Give me just a few minutes and I'll give you a better test case.

**Comment by evansolomon** [comment]
I'm trying to figure out how that overriding `this` behavior would be possible, even if you were trying to do it. I'd be very curious to see an example of how to reproduce that if you can come up with one.

**Comment by martindale** [comment]
Okay, it seems a bit more nuanced than I previously thought.  I didn't think it was possible either, and maybe I'm just completely incompetent... but I've stared at this code for almost a day now with no luck.  I've committed the changes that cause it to happen on the `broken` branch of snarl.

Apologies for dumping a repo on you, and I don't really expect much.  This is just a really, _really_ weird bug.

**Comment by evansolomon** [comment]
It's not clear to me that this is the source of your problem, but one thing I noticed is that your inheritance setup looks a bit off. Usually when you use node's `util.inherits` you'd also have something like (in this case) `EventEmitter.call(this)` in your child class' constructor. I don't immediately see why that would be related, but figured I'd mention it. Also fwiw I don't immediately see how the Slack client is related either.

**Comment by martindale** [comment]
I'm going to work my way backwards to reduce this to a much more clear test case.  I'll admit this is one of the strangest cases indeed, but when I removed the Slack client the `this` context was indeed preserved in that method.  EventEmitters were added later as an attempt to circumvent the problem.  Give me just a bit longer to reduce this down...

**Comment by l12s** [comment]
How do you trigger that function? Is it listening for a string from within a slack client it's attached to?

**Comment by martindale** [comment]
snarl uses inline triggers; `this example message asking for !help would trigger them`.  So they should be called from the context of a `Snarl` instance, but despite expectations, `this` inside of that function still points to the `Slack` instance.

**Comment by evansolomon** [comment]
Are you maybe just forgetting to bind a function?

```js
var events = require('events')
var e = new events.EventEmitter()

function C() {
  this.a = 1
}
C.prototype.thing = function () {
  console.log(this)
}

var c = new C()
e.on('wrong', c.thing)
e.on('right', c.thing.bind(c))

e.emit('wrong')
// logs the emitter instance
e.emit('right')
// logs the C instance
```

**Comment by evansolomon** [comment]
Pretty sure [this](https://github.com/martindale/snarl/blob/bd50fbe2d31078749c59a237ceeb5109fb505312/lib/snarl.js#L80) unbound callback is your primary problem. If you replace it with `self._interpret.bind(self)` I would expect it to work.

I think you have a secondary problem in the way you're only partially handling the false-y case for `self.triggers` in `_interpret`.
